

name: Update and Install apt-get

runs:
  using: "composite"
  steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install install PyOpenGL
          pip install PySide6==6.4.3
          pip install numpy
        shell: bash
      - name: make requirements file
        run: pip freeze > requirements.txt
        shell: bash