

name: Cached Python Setup

runs:
  using: "composite"
  steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # 3.10 is default
          python-version: '3.10'  
          cache: 'pip' # caching pip dependencies
          # Cacheing, by default, pins itself to changes in requirements.txt
          # I'm testing what overriding that means
          cache-dependency-path: carlynorama/GHActionsForOpenUSD/actions/python_cached_setup/requirements.txt
      - name: Upgrade
        run: |
          python -m pip install --upgrade pip
      - name: Install
        run: |
          pip install install carlynorama/GHActionsForOpenUSD/actions/python_cached_setup/requirements.txt