##
## GitHub Actions File
## https://github.com/carlynorama/GHActionsForOpenUSD/
##
## actions/python_cached_setup/action.yml
## Carlyn Maw 2023 Jul 21
##


name: Cached Python Setup

runs:
  using: "composite"
  steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # 3.10 is default
          python-version: '3.10'  
          cache: 'pip' # caching pip dependencies
          # Cacheing, by default, pins itself to changes in requirements.txt
          # I'm testing what overriding that means
          cache-dependency-path: carlynorama/GHActionsForOpenUSD/actions/python_cached_setup/requirements.txt@default_build_test
      - name: Upgrade
        shell: bash
        run: |
          python -m pip install --upgrade pip
      - name: Install
        shell: bash
        run: |
          pip install install -r carlynorama/GHActionsForOpenUSD/actions/python_cached_setup/requirements.txt@default_build_test