##
## GitHub Actions File
## https://github.com/carlynorama/GHActionsForOpenUSD/
##
## example_workflows/cached_default.yml
## Carlyn Maw 2023 Jul 21
##


name: Run on Default Flavor

on:
  push:
    branches: [ "default_build_test" ]
  pull_request:
    branches: [ "default_build_test" ]
      
jobs:
  build:
    name: Try Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3
      - name: apt-get setup
        uses: carlynorama/GHActionsForOpenUSD/actions/apt_get_update_install@main
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install install PyOpenGL
          pip install PySide6==6.4.3
          pip install numpy
      - name: make requirements file
        run: pip freeze
      - name: Restore OpenUSD (Repo and Build)
        id: cache-openusddf-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            OpenUSD_REPO
            OpenUSD_BUILD_DEFAULT
          key: ${{ runner.os }}-openusddf
      - name: Build Fresh
        if: steps.cache-openusddf-restore.outputs.cache-hit != 'true'
        uses: carlynorama/GHActionsForOpenUSD/actions/clone_and_build_default@main
      - name: Use Cached Build
        if: steps.cache-openusddf-restore.outputs.cache-hit == 'true'
        run: |
          echo "USD_REPO_DIR=$PWD/OpenUSD_REPO" >> $GITHUB_ENV
          echo "USD_BUILD_DIR=$PWD/OpenUSD_BUILD_DEFAULT" >> $GITHUB_ENV
      - name: Tell me about Environement
        run: |
          echo "-----"
          pwd  
          ls
          which python3
          python3 --version
          which python
          python --version
          echo $GITHUB_WORKSPACE
          echo $PATH
          echo $GITHUB_ENV
          echo .env
          echo "-----"
      - name: Save OpenUSD Cache (Repo & Build)
        id: cache-openusddf-save
        uses: actions/cache/save@v3
        with:
          path: |
            OpenUSD_REPO
            OpenUSD_BUILD_DEFAULT
          key: ${{ steps.cache-openusddf-restore.outputs.cache-primary-key }}   
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
      - name: Confirms Runs
      # if: steps.cache-openusddf-restore.outputs.cache-hit != 'true'
        run: |
            $USD_BUILD_DIR/bin/usdcat -h
      - name: Add OpenUSD Build to PATH and PYTHONPATH
        run: |
          export PYTHONPATH=$PYTHONPATH:$USD_BUILD_DIR/lib/python 
          echo "$USD_BUILD_DIR/bin" >> $GITHUB_PATH
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
      - name: Confirm in Path
        run: |
          echo "----- START Did it work?"
          echo $USD_BUILD_DIR
          echo $PYTHONPATH
          echo $PATH
          echo $GITHUB_PATH
          echo $GITHUB_ENV
          ls $USD_BUILD_DIR/bin/
          echo "-----"
          usdcat -h


