#   # Ubuntu latest has much of what is needed.
#   # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
#   # Still needed OpenGL

name: Update and Install apt-get

runs:
  using: "composite"
  steps:
    - name: Update apt-get 
      run: sudo apt-get update
      shell: bash
    - name: Set up packages (Linux)
      run: |
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      shell: bash

 