##
## GitHub Actions File
## https://github.com/carlynorama/GHActionsForOpenUSD/
##
## actions/hello_action/action.yml
## Carlyn Maw 2023 Jul 21
##

name: Example External Script

runs:
  using: "composite"
  steps:
    - name: Message
      run: echo "Nya-ha-ha! You Found Me!"
      shell: "bash"
