##
## GitHub Actions File
## https://github.com/carlynorama/GHActionsForOpenUSD/
##
## actions/clone_repo/action.yml
## Carlyn Maw 2023 Jul 21
##

name: Build Fresh No Python

runs:
  using: 'composite'
  steps:
    - name: Clone Pixar USD
      uses: actions/checkout@v3
      with:
        repository: PixarAnimationStudios/OpenUSD
        path: OpenUSD_REPO
    - name: Add Repo Location to GITHUB_ENV
      run: |
        echo "USD_REPO_DIR=$PWD/OpenUSD_REPO" >> $GITHUB_ENV
      shell: bash