name: Build Fresh No Python

runs:
  using: 'composite'
  steps:
    - name: Clone Pixar USD
      uses: actions/checkout@v3
      with:
        repository: PixarAnimationStudios/OpenUSD
        path: OpenUSD_REPO
    - name: Add Repo Location to GITHUB_ENV
      run: |
        echo "USD_REPO_DIR=$PWD/OpenUSD_REPO" >> $GITHUB_ENV
      shell: bash