# see https://github.com/pablode/USD/blob/v22.11-ci/.github/workflows/deploy-release.yml
# https://github.com/usd-wg/assets/pull/49
# https://github.com/usd-wg/assets/pull/48 

# About Ubuntu-Latest
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

# About Cache Actions
# https://github.com/marketplace/actions/cache

name: Build Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3
      - name: apt-get setup
        uses: ./actions/hello_action
      - name: apt-get setup
        uses: carlynorama/GHActionsForOpenUSD/actions/hello_action@main
