# Proof of concept

name: Can you see me?

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3
      - name: apt-get setup
        uses: ./actions/hello_action
      - name: apt-get setup
        uses: carlynorama/GHActionsForOpenUSD/actions/hello_action@main
